import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:     ['Inter', 'var(--font-dm-sans)', 'ui-sans-serif', 'system-ui'],
        headline: ['Manrope', 'var(--font-syne)', 'ui-sans-serif'],
        body:     ['Inter', 'var(--font-dm-sans)', 'ui-sans-serif'],
        label:    ['Inter', 'ui-sans-serif'],
        mono:     ['var(--font-jetbrains)', 'ui-monospace'],
      },
      colors: {
        // MD3 shell tokens (direct hex — always resolved)
        "background":                "#0b1326",
        "surface":                   "#0b1326",
        "surface-dim":               "#0b1326",
        "surface-bright":            "#31394d",
        "surface-variant":           "#2d3449",
        "surface-tint":              "#bdc2ff",
        "surface-container-lowest":  "#060e20",
        "surface-container-low":     "#131b2e",
        "surface-container":         "#171f33",
        "surface-container-high":    "#222a3d",
        "surface-container-highest": "#2d3449",
        "on-background":             "#dae2fd",
        "on-surface":                "#dae2fd",
        "on-surface-variant":        "#c7c4d7",
        "inverse-surface":           "#dae2fd",
        "inverse-on-surface":        "#283044",
        "outline":                   "#908fa0",
        "outline-variant":           "#464554",
        "primary":                   "#bdc2ff",
        "on-primary":                "#131e8c",
        "primary-container":         "#7c87f3",
        "on-primary-container":      "#081486",
        "primary-fixed":             "#e0e0ff",
        "primary-fixed-dim":         "#bdc2ff",
        "inverse-primary":           "#4953bc",
        "secondary":                 "#b9c8de",
        "on-secondary":              "#233143",
        "secondary-container":       "#39485a",
        "on-secondary-container":    "#a7b6cc",
        "tertiary":                  "#ffb783",
        "on-tertiary":               "#4f2500",
        "tertiary-container":        "#d97721",
        "error":                     "#ffb4ab",
        "on-error":                  "#690005",
        "error-container":           "#93000a",
        "on-error-container":        "#ffdad6",
        // Legacy CSS-var tokens kept for inner components
        foreground: "var(--text-primary)",
        accent: { DEFAULT: '#4F70FF', hover: '#6B87FF' },
        success: '#00D87A',
        warning: '#F5A200',
        danger:  '#FF4545',
      },
    },
  },
  plugins: [],
};
export default config;
